{% set python_min = '3.10' %}
{% set name = "auto-intersphinx" %}
{% set version = "1.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 4d904c1571a646ad0800deb9b3620bc0dc33f70557fa52d50016cae3c5eaba3a

build:
  entry_points:
    - auto-intersphinx = auto_intersphinx.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - versioningit
    - pip
  run:
    - python >={{ python_min }}
    - sphinx
    - packaging
    - requests
    - lxml

test:
  source_files:
    - tests
  imports:
    - auto_intersphinx
  commands:
    - pip check
    - auto-intersphinx --help
    - pytest -sv tests
  requires:
    - pip
    - pytest
    - python {{ python_min }}

about:
  home: https://github.com/idiap/auto-intersphinx
  doc_url: https://auto-intersphinx.readthedocs.io
  dev_url: https://github.com/idiap/auto-intersphinx
  summary: Automatic links direct project dependencies to the intersphinx catalog
  license: BSD-3-Clause
  license_file: LICENSES/BSD-3-Clause.txt

extra:
  recipe-maintainers:
    - Yannick-Dayer
    - anjos
