{% set name = "auto-intersphinx" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/auto-intersphinx-{{ version }}.tar.gz
  sha256: 4301d3604d3469378b2647187c98975e6f0a402382ce522a8d00c7cc63686853

build:
  entry_points:
    - auto-intersphinx = auto_intersphinx.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=61.0.0
    - wheel
    - pip
  run:
    - python >=3.9
    - sphinx
    - packaging
    - requests
    - lxml

test:
  source_files:
    - tests
  imports:
    - auto_intersphinx
  commands:
    - pip check
    - auto-intersphinx --help
    - pytest -sv tests
  requires:
    - pip
    - pytest

about:
  home: https://gitlab.idiap.ch/software/auto-intersphinx
  doc_url: https://auto-intersphinx.readthedocs.io
  dev_url: https://gitlab.idiap.ch/software/auto-intersphinx
  summary: Automatic links direct project dependencies to the intersphinx catalog
  license: BSD-3-Clause
  license_file: LICENSES/BSD-3-Clause.txt

extra:
  recipe-maintainers:
    - anjos
